name: mobile_app
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
#  melos: ^6.3.2
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  common_functions:



flutter:
  assets:
#    - assets/



